# This is a config for E2B sandbox template.
# You can use template ID (gndmbgnotsunx9z45mf4) or template name (silo-nextjs-rishi) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("silo-nextjs-rishi") # Sync sandbox
# sandbox = await AsyncSandbox.create("silo-nextjs-rishi") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('silo-nextjs-rishi')

team_id = "8af661ae-22b8-4448-b07a-d00715484eec"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "silo-nextjs-rishi"
template_id = "gndmbgnotsunx9z45mf4"
